### ISSUE TITLE
float precision issue

### ISSUE THREAD

**Issue by YikSanChan** [berkeley-cs186/sp21-rookiedb#2]
In https://github.com/berkeley-cs186/sp21-rookiedb/blob/master/src/test/java/edu/berkeley/cs186/database/index/TestLeafNode.java#L116

The for loop goes like:

```java
for (int i = 0; i < (int) Math.ceil(1.5 * d * fillFactor); ++i) { ... }
```

The comment https://github.com/berkeley-cs186/sp21-rookiedb/blob/master/src/test/java/edu/berkeley/cs186/database/index/TestLeafNode.java#L108 says:
```
// Bulk loads with 60% of a leaf's worth, then checks that the
// leaf didn't split.
```

However, `(int) Math.ceil(1.5 * d * fillFactor)` evaluates to 7, not 6.

Maybe do `(int) Math.ceil(2 * d * 0.6)` works better, as 1.5 introduces precision issue.

**Comment by ckw017** [comment]
We'll fix that for future versions in later semesters, thanks.
