### ISSUE TITLE
Consider "version control" the educational db implementation?

### ISSUE THREAD

**Issue by YikSanChan** [berkeley-cs186/sp21-rookiedb#3]
Hi,

First of all, the codebase is great!

I wonder if it is possible to really "version control" the educational db implementation in the way that we won't need to have:
- fa20-moocbase
- sp21-rookiedb
- fa21-hehedb
- etc

An example can be found https://github.com/cmu-db/bustub for CMU 15-445 https://15445.courses.cs.cmu.edu/fall2020/

Thank you!

**Comment by ckw017** [comment]
We set access to previous semester's versions of the codebase to private at the end of each semester, so this isn't necessary.
