### ISSUE TITLE
I 'm confused about the role  of probeFirst variable

### ISSUE THREAD

**Issue by sjx782392329** [berkeley-cs186/sp21-rookiedb#5]
https://github.com/berkeley-cs186/sp21-rookiedb/blob/3c0a485fd2b5ee0a429c62ccb354ff3bb8183107/src/main/java/edu/berkeley/cs186/database/query/join/GHJOperator.java#L82

![image](https://user-images.githubusercontent.com/33451661/110756305-fb661f80-8284-11eb-9fc2-9fcb38ef2f58.png)
In this code segment, **we can know which Partition is buildRecords**. Why we need this variable `probeFirst`

**Comment by ckw017** [comment]
The hash and probe partitions are not necessarily in the same order as the original "left" and "right" partitions, however when you join you should still concatenate in the correct order.
